export const CORE_SIDE_NAV = [
  { name: "Dashboard", url: "/admin/dashboard", icon: "ClipboardDocumentIcon" },
  { name: "My Research", url: "/admin/research", icon: "RectangleStackIcon" },
  {
    name: "My Feedback",
    url: "/admin/feedback",
    icon: "AdjustmentsHorizontalIcon",
  },
  { name: "Profile", url: "/admin/profile", icon: "UserIcon" },
];

export const DEFAULT_PAGE_SIZE = 6;
export const MAX_FILE_UPLOAD_SIZE = 3145728; //3MB

export const TEAM_LIST = [
  {
    name: "Prof. KC Santosh",
    role: "Professor (AI) & Chair, Department of Computer Science, USD",
    description: "Founding Director, AI Research Lab ",
    avatarSrc: "/images/team/kc-profile.jpg",
    research:
      "Green computing, active learning, machine learning, AI, ethical AI, explainable AI",
    website: "https://kc-santosh.org/",
    linkedin: "https://www.linkedin.com/in/santoshkc",
  },
  {
    name: "Dr. Rodrigue Rizk",
    role: "Assistant Professor, Department of Computer Science, USD",
    description: "Vice-Director, Engineering",
    avatarSrc: "/images/team/rod.jpg",
    research:
      "Artificial Intelligence, Deep Learning, Reinforcement Learning, Quantum Computing, Physics-Inspired Computing, Healthcare, Emerging Technologies, Agentic AI, Physical AI",
    website: "",
    linkedin: "https://www.linkedin.com/in/rodrigue-rizk",
  },
  {
    name: "Dr. Longwei Wang",
    role: "Assistant Professor, Department of Computer Science, USD",
    description: "Vice-Director, Research",
    avatarSrc: "/images/team/wang.jpeg",
    research: "AI and machine learning",
    website: "",
    linkedin: "",
  },
  {
    name: "Dr. Debesh Jha",
    role: "Assistant Professor (Visiting), Department of Computer Science, USD",
    description: "Member, AI Research Lab",
    avatarSrc: "/images/team/debesh.jpg",
    research: "Machine learning, computer vision, healthcare informatics ",
    website: "https://debeshjha.com/",
    linkedin: "https://www.linkedin.com/in/debesh-jha-ph-d-071462aa",
  },
  {
    name: "Dr. Lina S Chato",
    role: "Assistant Professor (Visiting), Department of Computer Science, USD",
    description: "Member, AI Research Lab",
    avatarSrc: "/images/team/lina.jpg",
    research:
      "AI, Computer Vision, Signal/Image Processing, Multimodal Medical Data Processing",
    website: "",
    linkedin: "https://www.linkedin.com/in/lina-s-chato-397a5031",
  },
  {
    name: "Dr. Srikanth Baride ",
    role: "Assistant Professor (Visiting), Department of Computer Science, USD",
    description: "Member, AI Research Lab",
    avatarSrc: "/images/team/srikant.jpg",
    research: "Colocation Pattern Mining, and Data Science",
    website: "",
    linkedin: "https://www.linkedin.com/in/srikanth-baride",
  },
  {
    name: "Dr. Nand K Yadav",
    role: "PostDoc, Department of Computer Science, USD",
    description: "Member, AI Research Lab ",
    avatarSrc: "/images/team/nand.jpg",
    research: "Machine learning, GAN, biometrics",
    website: "",
    linkedin: "https://in.linkedin.com/in/nand-yadav-891883262",
  },
];

export const PHD_STUDENTS = [
  {
    name: "Nicholas Rasmussen",
    program: "PhD. In Data science and Engineering",
    position: "Research Assistant",
    research: "Signal Processing, Computer Vision, Bioacoustics.",
    linkedin: "https://www.linkedin.com/in/nicholas-rasmussen-022902174/",
  },
  {
    name: "Casey Wall",
    program: "PhD Student",
    position: "Research Assistant",
    research: "Machine Learning & Computer Vision",
    linkedin: "",
  },
  {
    name: "David Cortes",
    program: "PhD Student",
    position: "Research Assistant",
    research: "Machine Learning & Computer Vision",
    linkedin: "",
  },
  {
    name: "Priyam Pandey",
    program: "PhD Student",
    position: "Research Assistant",
    research: "Machine Learning & Computer Vision",
    linkedin: "",
  },
];

export const MASTERS_STUDENTS = [
  {
    name: "Sony Reddy Gurram",
    program: "MSc. Computer Science",
    position: "Teaching Assistant",
    research: "Machine Learning & Computer Vision",
    linkedin: "https://linkedin.com/in/sony-reddy-gurram-715450229",
  },
  {
    name: "Sainath Vaddi",
    program: "M.S. Computer Science",
    position: "Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "https://linkedin.com/in/vaddi-sainath-146b911a3",
  },
  {
    name: "Puskal Khadka",
    program: "M.S. Computer Science",
    position: "Graduate Assistant",
    research: "Deep Learning, Computer Vision",
    linkedin: "https://www.linkedin.com/in/puskal-khadka-910971188/",
  },
  {
    name: "Deborah Asamoah",
    program: "MS. Computer Science",
    position: "Teaching Assistant",
    research: "Machine Learning & Computer Vision",
    linkedin: "https://www.linkedin.com/in/deborah-asamoah/",
  },
  {
    name: "Anupam Dhakal",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, LLM and Computer Vision",
    linkedin: "https://www.linkedin.com/in/anupamdkl/",
  },
  {
    name: "Robin Narsingh Ranabhat",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Neural Networks Robustness and Interpretability",
    linkedin: "https://www.linkedin.com/in/robinranabhat/",
  },
  {
    name: "Thoyajakasha Kashyap Kristipati",
    program: "MSc. Computer Science Artificial Intelligence",
    position: "Research Assistant",
    research: "Deep Learning, GAN and Computer Vision",
    linkedin: "https://www.linkedin.com/in/thoyajaksha-kashyap-kristipati/",
  },
  {
    name: "Pooja Singh",
    program: "MSc. Computer Science",
    position: "Graduate Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Chenchaiah Mekalathu",
    program: "MSc. Computer Science",
    position: "Graduate Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Kanishka Parankusham",
    program: "MSc. Computer Science",
    position: "Graduate Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Neerajdattu Dudam",
    program: "MSc. Computer Science",
    position: "Graduate Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Akshay Reddy",
    program: "MSc. Computer Science",
    position: "Graduate Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Mohammad Navid Nayyem",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Krishna Phanindra Marupaka",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Deepika Nuthalapati",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Satya Mouli Dhangati",
    program: "MSc. Computer Science",
    position: "Graduate Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Sivani Maddepalli",
    program: "MSc. Computer Science",
    position: "Graduate Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Aashish Ghimire",
    program: "MSc. Computer Science",
    position: "Graduate Teaching Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Sabin Adhikari",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Jayakumar Pujar",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Aniket Kumar",
    program: "MSc. Computer Science",
    position: "Research Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
  {
    name: "Jeevan Kaphle",
    program: "MSc. Computer Science",
    position: "Graduate Assistant",
    research: "Machine Learning, and Computer Vision",
    linkedin: "",
  },
];
